### ISSUE TITLE
Please add 'last app' feature

### ISSUE THREAD

**Issue by kmcbest** [tkgktyk/ForceTouch#1]
I would like to request a new feature in 'tools' menu when defining a force touch action. That would be 'last app' so that I can switch between 2 recently used APPS quickly. Just as 'alt +tab' in Windows system.

Thank you.

**Comment by tkgktyk** [comment]
Hello,
Thank you for your feedback. I'm planning the action, but I need time
because the API to get recents was changed on Lollipop.
However, probably emulating 'alt + tab' key realizes this action as you
said!

Regards,
Takagi

2015-08-11 18:58 GMT+09:00 kmcbest notifications@github.com:
