### ISSUE TITLE
I  can't  get this app to work on my Samsung  Galaxy  Tab 4 (rooted )

### ISSUE THREAD

**Issue by rcolitz** [tkgktyk/ForceTouch#2]
I  may be   doing  something  wrong  I just don't  know .  This is  app will display  the buttons but then a few minutes  later it's  like it's  not installed  and then I can't  get the buttons to appear. So I reboot and try it again . Same thing happens .

**Comment by tkgktyk** [comment]
Turn on "Disabled-Action Toast" and "Enabled-Action Toast" in General setting, and then test FTD again. These options show toast when you force touch for debug. If you see toasts, FTD works well.

Floating Action buttons work independent of Xposed module. Buttons require its notification usually. If the notification is destroyed by system, app or others, you can't see the buttons, but toasts appear.
