### ISSUE TITLE
wiggle touch is more sensitive in swipe input app.

### ISSUE THREAD

**Issue by yyBeta** [tkgktyk/ForceTouch#3]
One suggestion: Could you please add the option of blocking the function while typing words in input app, because swiping gestures in some swipe input app make it more sensitive to activate the wiggle touch. I tried to add the input app into the blocklist but it doesn't work because it just judged the app you're typing words in as the foreground app.

**Comment by tkgktyk** [comment]
Although I use "Google Japanese Input" for keypad, Blacklist works well. To take effect, You need to stop app process, "Google Japanese Input" for me, by restarting your phone or force stop button in global app setting that is placed in phone's settings -> Apps.

**Comment by yyBeta** [comment]
Oops, I just restarted my system and it works well now. Thanks a lot, it's really an awesome app which could be called Pandora Tool wwwwwww
